source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'
gem 'rack-cors'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'active_model_serializers', '~> 0.10.13'
gem 'sidekiq', '~> 7.2'
gem 'redis', '~> 5.0'
gem 'pg_search', '~> 2.3'
gem 'image_processing', '~> 1.12'
gem 'aws-sdk-s3', '~> 1.0', require: false
gem 'actioncable'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

