#!/bin/bash
#
# GitLab CE Deployment Script
# Deploys GitLab CE with Infisical secrets management
#
# Usage:
#   ./deploy.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$SCRIPT_DIR"

echo "=== GitLab CE Deployment ==="
echo ""

# Check if Infisical CLI is available
if ! command -v infisical &> /dev/null; then
    echo "Error: Infisical CLI not found. Please install it first."
    exit 1
fi

# Generate secure random password for GitLab root
GITLAB_ROOT_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)
GITLAB_DB_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)

echo "=== Setting GitLab secrets in Infisical ==="
echo ""

# Load Infisical project ID from .workspace/.env (extract specific vars only)
if [ -f "$INFRA_ROOT/.workspace/.env" ]; then
    export INFISICAL_PROJECT_ID=$(grep "^INFISICAL_PROJECT_ID=" "$INFRA_ROOT/.workspace/.env" | cut -d'=' -f2 | tr -d "'\"")
    export POSTGRES_USER=$(grep "^POSTGRES_USER=" "$INFRA_ROOT/.workspace/.env" | cut -d'=' -f2 | tr -d "'\"")
fi

# Set GitLab secrets in Infisical
echo "Setting secrets in Infisical..."
echo ""
echo "⚠️  Note: Infisical secrets need to be set via web UI or with authenticated CLI."
echo "   Secrets will be loaded from .workspace/.env (generated by Infisical Agent)."
echo ""
echo "Please set these secrets in Infisical web UI at https://infisical.freqkflag.co:"
echo "  - GITLAB_DOMAIN=gitlab.freqkflag.co"
echo "  - GITLAB_DB_USER=gitlab"
echo "  - GITLAB_DB_PASSWORD=$GITLAB_DB_PASSWORD"
echo "  - GITLAB_DB_NAME=gitlab"
echo "  - GITLAB_ROOT_PASSWORD=$GITLAB_ROOT_PASSWORD"
echo "  - GITLAB_SSH_PORT=2224"
echo ""
echo "Or use CLI (requires authentication):"
if [ -n "${INFISICAL_PROJECT_ID:-}" ]; then
    echo "  infisical secrets set --projectId $INFISICAL_PROJECT_ID --env prod --path /prod GITLAB_DOMAIN='gitlab.freqkflag.co'"
    echo "  infisical secrets set --projectId $INFISICAL_PROJECT_ID --env prod --path /prod GITLAB_DB_USER='gitlab'"
    echo "  infisical secrets set --projectId $INFISICAL_PROJECT_ID --env prod --path /prod GITLAB_DB_PASSWORD='$GITLAB_DB_PASSWORD'"
    echo "  infisical secrets set --projectId $INFISICAL_PROJECT_ID --env prod --path /prod GITLAB_DB_NAME='gitlab'"
    echo "  infisical secrets set --projectId $INFISICAL_PROJECT_ID --env prod --path /prod GITLAB_ROOT_PASSWORD='$GITLAB_ROOT_PASSWORD'"
    echo "  infisical secrets set --projectId $INFISICAL_PROJECT_ID --env prod --path /prod GITLAB_SSH_PORT='2224'"
fi
echo ""
# Continue automatically (secrets will be loaded from .workspace/.env via Infisical Agent)
echo "Continuing with deployment..."

echo ""
echo "=== Secrets configured ==="
echo "GitLab Root Password: $GITLAB_ROOT_PASSWORD"
echo "GitLab DB Password: $GITLAB_DB_PASSWORD"
echo ""
echo "⚠️  IMPORTANT: Save these passwords securely!"
echo "⚠️  Change the root password after first login!"
echo ""

# Create database if it doesn't exist
echo "=== Creating GitLab database ==="
echo ""

# Check if PostgreSQL is running (check for any postgres container)
POSTGRES_CONTAINER=$(docker ps --format "{{.Names}}" | grep -i postgres | head -1)
if [ -n "$POSTGRES_CONTAINER" ]; then
    echo "PostgreSQL container found: $POSTGRES_CONTAINER"
    echo "Creating GitLab database and user..."
    
    # Try to get POSTGRES_USER from .workspace/.env or use default
    if [ -f "$INFRA_ROOT/.workspace/.env" ]; then
        source "$INFRA_ROOT/.workspace/.env"
    fi
    
    # Create database and user (if they don't exist)
    docker exec -i "$POSTGRES_CONTAINER" psql -U "${POSTGRES_USER:-postgres}" -d postgres <<EOF 2>&1 | grep -v "already exists" || true
CREATE USER gitlab WITH PASSWORD '$GITLAB_DB_PASSWORD';
CREATE DATABASE gitlab OWNER gitlab;
GRANT ALL PRIVILEGES ON DATABASE gitlab TO gitlab;
EOF
    echo "Database setup complete (or already exists)"
else
    echo "⚠️  Warning: PostgreSQL container not found."
    echo "Please ensure PostgreSQL is running and create the database manually:"
    echo "  CREATE USER gitlab WITH PASSWORD '$GITLAB_DB_PASSWORD';"
    echo "  CREATE DATABASE gitlab OWNER gitlab;"
    echo "  GRANT ALL PRIVILEGES ON DATABASE gitlab TO gitlab;"
fi

echo ""
echo "=== Deploying GitLab CE ==="
echo ""

# Deploy using docker compose
cd "$SCRIPT_DIR"
DEVTOOLS_WORKSPACE="$INFRA_ROOT" docker compose up -d

echo ""
echo "=== Deployment complete ==="
echo ""
echo "GitLab is starting up. This may take 5-10 minutes on first boot."
echo ""
echo "Access GitLab at: https://gitlab.freqkflag.co"
echo "Initial root password: $GITLAB_ROOT_PASSWORD"
echo ""
echo "To view logs: docker compose logs -f gitlab"
echo "To check status: docker exec -it gitlab gitlab-ctl status"
echo ""
