#!/bin/bash
# Script to create FL Clone documentation page in WikiJS
# This script provides instructions and can be used to prepare the content

WIKIJS_URL="https://wiki.freqkflag.co"
DOC_FILE="/root/infra/projects/FL_Clone/WIKIJS_DOCUMENTATION.md"

echo "=========================================="
echo "FL Clone WikiJS Page Creation"
echo "=========================================="
echo ""
echo "WikiJS is accessible at: $WIKIJS_URL"
echo ""
echo "To create the FL Clone documentation page:"
echo ""
echo "1. Log in to WikiJS at $WIKIJS_URL"
echo "2. Navigate to: Create > Page"
echo "3. Set the following:"
echo "   - Title: 'FL Clone - Building Process Documentation'"
echo "   - Path: 'projects/fl-clone-building-process'"
echo "   - Description: 'Complete documentation of the FL Clone social platform build process'"
echo "   - Content: Copy from $DOC_FILE"
echo ""
echo "4. Set page properties:"
echo "   - Editor: Markdown"
echo "   - Category: Projects"
echo "   - Tags: fl-clone, rails, vue, social-platform, twist3dkinkst3r"
echo ""
echo "5. Publish the page"
echo ""
echo "=========================================="
echo "Content file location: $DOC_FILE"
echo "=========================================="
echo ""
echo "You can view the content with:"
echo "  cat $DOC_FILE"
echo ""
echo "Or copy it directly:"
echo "  cat $DOC_FILE | xclip -selection clipboard"
echo "  (then paste into WikiJS editor)"
echo ""

