#!/usr/bin/env bash
#
# Ingest a harvested archive into nodes/<device>/compose/ and normalize files.
#
# Usage: scripts/ingest_harvest.sh <device> <harvest_archive>

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "usage: $0 <device> <harvest_archive> [repo_root]" >&2
  exit 1
fi

DEVICE="$1"
HARVEST_ARCHIVE="$2"
REPO_ROOT="${3:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
NODES_ROOT="${REPO_ROOT}/nodes/${DEVICE}"
COMPOSE_DEST="${NODES_ROOT}/compose"
ENV_DEST_DIR="${NODES_ROOT}/env"
ENV_EXAMPLE="${ENV_DEST_DIR}/.env.example"

require_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "[ERR] required command not found: ${cmd}" >&2
    exit 1
  fi
}

require_cmd tar
require_cmd yq

if [[ ! -f "${HARVEST_ARCHIVE}" ]]; then
  echo "[ERR] harvest archive not found at ${HARVEST_ARCHIVE}" >&2
  exit 1
fi

if [[ ! -d "${NODES_ROOT}" ]]; then
  echo "[ERR] nodes directory missing at ${NODES_ROOT}" >&2
  exit 1
fi

WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT

tar -C "${WORKDIR}" -xzf "${HARVEST_ARCHIVE}"

# unwrap single top-level directory if present
HARVEST_PAYLOAD="${WORKDIR}"
if [[ "$(find "${WORKDIR}" -mindepth 1 -maxdepth 1 -type d | wc -l)" -eq 1 ]]; then
  HARVEST_PAYLOAD="$(find "${WORKDIR}" -mindepth 1 -maxdepth 1 -type d)"
fi

mkdir -p "${COMPOSE_DEST}"
rm -rf "${COMPOSE_DEST:?}/"*

# Find compose files in the harvest payload
mapfile -t COMPOSE_FILES < <(find "${HARVEST_PAYLOAD}" -type f \( -name '*.yml' -o -name '*.yaml' \) | sort)

if [[ ${#COMPOSE_FILES[@]} -eq 0 ]]; then
  echo "[WARN] no compose files discovered inside ${HARVEST_ARCHIVE}" >&2
fi

for src in "${COMPOSE_FILES[@]}"; do
  rel_path="${src#"${HARVEST_PAYLOAD}/"}"
  dest="${COMPOSE_DEST}/${rel_path}"
  mkdir -p "$(dirname "${dest}")"
  cp "${src}" "${dest}"
  # Delete deprecated "version:" key if present
  if yq eval 'has("version")' "${dest}" >/dev/null 2>&1; then
    yq eval 'del(.version)' -i "${dest}"
  fi
done

mkdir -p "${ENV_DEST_DIR}"

# Extract environment variable placeholders from compose files
declare -A ENV_PLACEHOLDERS=()
while IFS= read -r match; do
  key="$(echo "${match}" | sed -E 's/^\$\{([A-Za-z0-9_]+).*$/\1/')"
  if [[ -n "${key}" ]]; then
    ENV_PLACEHOLDERS["${key}"]=1
  fi
done < <(grep -Roh '\${[A-Za-z0-9_][A-Za-z0-9_:-]*}' "${COMPOSE_DEST}" 2>/dev/null || true)

{
  echo "# autogenerated placeholder file"
  if [[ ${#ENV_PLACEHOLDERS[@]} -eq 0 ]]; then
    echo "# (no placeholders detected in compose files)"
  else
    for key in "${!ENV_PLACEHOLDERS[@]}"; do
      echo "${key}="
    done | sort
  fi
} > "${ENV_EXAMPLE}"

echo "[+] Ingested $((${#COMPOSE_FILES[@]})) compose files into ${COMPOSE_DEST}"
echo "[+] Generated env placeholder file at ${ENV_EXAMPLE}"
