version = 5.1.0
archive_dir = /etc/letsencrypt/archive/vault.freqkflag.co
cert = /etc/letsencrypt/live/vault.freqkflag.co/cert.pem
privkey = /etc/letsencrypt/live/vault.freqkflag.co/privkey.pem
chain = /etc/letsencrypt/live/vault.freqkflag.co/chain.pem
fullchain = /etc/letsencrypt/live/vault.freqkflag.co/fullchain.pem
[renewalparams]
account = 4f134315d358b367ca708b335234d4d7
authenticator = dns-cloudflare
dns_cloudflare_credentials = /etc/letsencrypt/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
